/**
 * dz dialect sentence API
 * Sentences API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SentenceResponseDto } from './sentence-response-dto';


export interface PaginatedSentenceResponseDto { 
    elements: Array<SentenceResponseDto>;
    length: number;
    pageIndex: number;
    pageSize: number;
}

